"Hello world sample, please remove"
type HelloWorldmsname{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFrommsname: HelloWorldmsname
}

type Subscription {
  "Hello world sample, please remove"
  msnameHelloWorldSubscription: HelloWorldmsname  
}