enum EventSourcingMonitorTimeFrameType{
  MINUTE
  HOUR
  DAY
  MONTH
  YEAR
}
"Basic key-value type"
type EventSourcingMonitorKeyValue{
  key: String
  value: Int
}

type EventSourcingMonitorInnerKeyValue{
  key: String
  value: [EventSourcingMonitorKeyValue]
}

type EventSourcingMonitorEventTypes{
  key: String
  value: [EventSourcingMonitorInnerKeyValue]
}



type EventSourcingMonitorTimeFrame{
  id: BigInt
  globalHits: Int
  eventTypeHits: [EventSourcingMonitorKeyValue]
  userHits: [EventSourcingMonitorKeyValue]
  eventTypes: [EventSourcingMonitorEventTypes]
  aggregateTypeHits: [EventSourcingMonitorKeyValue]
}


"Queries session"
type Query {
  "Hello world sample, please remove"
  # getHelloWorldFromEventSourcingMonitor: HelloWorldEventSourcingMonitor
  getTimeFramesSinceTimestampFromEventSourcingMonitor( timeFrameType:EventSourcingMonitorTimeFrameType!, initTimestamp: BigInt!, quantity: Int!): [EventSourcingMonitorTimeFrame]
}

type Subscription {
  EventMonitorUpdateAvailable: BigInt  
}
