"Hello world sample, please remove"
type HelloWorldEventSourcingMonitor{
  "text"
  sn: String!  
}

type Query {
  "Hello world sample, please remove"
  getHelloWorldFromEventSourcingMonitor: HelloWorldEventSourcingMonitor
}

type Subscription {
  "Hello world sample, please remove"
  EventSourcingMonitorHelloWorldSubscription: HelloWorldEventSourcingMonitor  
}